# Generated by Django 4.0.3 on 2022-04-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=254)),
                ('price', models.FloatField(default=0)),
                ('author_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
